apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: fare-service
  name: fare-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fare-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: fare-service
    spec:
      containers:
        - env:
            - name: eureka.client.service-url.defaultZone
              value: http://discovery-server:8761/eureka
            - name: spring.datasource.password
              value: password
            - name: spring.datasource.url
              value: jdbc:postgresql://db:5432/postgres
            - name: spring.datasource.username
              value: postgres
          image: sangameshwar18/fare-service:1.0.0
          name: fare-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
